[platformio]
src_dir = esp32/src
include_dir = esp32/include
lib_dir = esp32/lib
test_dir = esp32/test

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
    -D MQTT_MAX_PACKET_SIZE=1024
lib_deps = 
    knolleary/PubSubClient @ ^2.8
